# 사용할 PHP 런타임을 지정합니다.
runtime: php82

# PHP 확장 프로그램을 활성화합니다. (Supabase의 Postgres DB 사용을 위함)
runtime_config:
  extensions:
    - pdo_pgsql
    - curl

# 환경 변수를 설정합니다.
env_variables:
  # 코드이그나이터 환경을 'production'으로 설정 (오류 방지 핵심!)
  CI_ENVIRONMENT: 'production'

# 앱 진입점을 'public' 폴더로 지정합니다.
entrypoint: 'serve public/index.php'

# 모든 요청을 public/index.php로 전달합니다.
handlers:
  - url: /.*
    script: auto