name: Build and deploy PHP app to Azure Web App - ci4test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json
          ini-values: post_max_size=256M, upload_max_filesize=256M, max_execution_time=300

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: 'composer.json'

      - name: Run composer install
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          composer validate --no-check-publish
          composer install --prefer-dist --no-progress --no-dev --optimize-autoloader

      - name: Create CI4 required directories
        run: |
          mkdir -p writable/cache
          mkdir -p writable/logs
          mkdir -p writable/session
          mkdir -p writable/uploads
          chmod -R 755 writable

      - name: Copy environment file
        run: |
          if [ -f .env.example ]; then
            cp .env.example .env
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'ci4test'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CI4TEST }}
          package: .